### ISSUE TITLE
it is unclear what "linuxPackages.nvidia_x11" is supposed to be for non-nvidia

### ISSUE THREAD

**Issue by donbright** [deepfire/nix-install-vendor-gl#8]
hello. I am trying to extend the script to Intel i915 and also software VMware / Mesa llvmpipe (by setting LIBGL_ALWAYS_SOFTWARE=1). However i am stuck at trying to figure out what the equivalent of linuxPackages.nvidia_x11 should be? I can't find any similar packages for intel nor for the software-mode of mesa. Can you help? Thanks

```

nixpkgs_vendorgl_attribute() {
        if test ! -z "${arg_nixpkgs_vendorgl_attr}"
        then vendorgl_attribute=${arg_nixpkgs_vendorgl_attr}
        else case ${vendorgl} in
                     nvidia ) echo 'linuxPackages.nvidia_x11';; esac; fi; }
```

**Comment by deepfire** [comment]
@donbright, it's an excellent question -- one that I have already thought about as well.

Perhaps @cleverca22 may know something.

**Comment by cleverca22** [comment]
`linuxPackages.nvidia_x11` is the kernel side drivers for nvidia, which probably wont work outside of nixos
it also contains the userland libraries that are compatible with those kernel drivers

you probably want to refer to these modules, to see where nixos gets the drivers from

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/ati.nix

**Comment by deepfire** [comment]
@cleverca22, `linuxPackages.nvidia_x11` works for me on SteamOS, at least -- which was the raison d'etre for `nix-install-vendor-gl` for me..

**Comment by cleverca22** [comment]
ah, i dont have steamos on anything, but i do have steam working under nixos

**Comment by deepfire** [comment]
The key point is that it's non-Nixos.  I've also tested `nix-install-vendor-gl` on Ubuntu, as can be seen on the test matrix: https://github.com/deepfire/nix-install-vendor-gl#osgpu-test-matrix

**Comment by donbright** [comment]
@cleverca22 said "linuxPackages.nvidia_x11 is the kernel side drivers for nvidia,"

yes thanks, quite interesting, but i am still a bit flummoxed. I can see that in non-nixos, I am having trouble finding DRI open source video drivers like nouveau_dri.so  or i965_dri.so. the Nix Mesa package doesn't seem to contain any of the open source DRI drivers.  so i am not even sure if there is an equivalent package. on normal system these dri typically live under  /usr/lib/x86_64-linux-gnu/dri/i915_dri.so which is dynamically loaded with dlopen() by Mesa's libGL.so at runtime. (You have to use strace -f glxinfo 2>&1 |  less or some such to actually see this in action) 

Interesting that Mesa open source drivers dont seem to need a specialized extremely specific version kernel module like nvidia does. ... i could be wrong but... 

---------

as for linuxPackages.nvidia_x11, i am a bit confused if  nix itself is running modprobe on these or ???? that seems to be the crucial compatibility question - if nvidia requires kernel modules keyed to a specific kernel version then it may be difficult to have various flavors of linux using a specific kernel version driver module. I say this because i have been compiling lots of wifi drivers lately and even being off by a single patchlevel can make the .ko module unloadable.  i could be wrong but...

The only way to be sure is to test.... the trouble is that to test something like this, you really need a machine with an Nvidia card that can multi-boot to multiple different linuxes. Its not possible to test inside a virtual machine as far as i know (are there any VMs with Nvidia card emulators?). I am building a machine like that now but it takes some time. different versions of linux do not make it always easy to install proprietary drivers. And it is an older card so im not sure if results will be relevant to newer cards.

**Comment by donbright** [comment]
closing, obsolete question, not sure if i have these machines anymore
